generations:
  - output: "luna.tex"
    n_page: 10
    page_offset: 51
    questions_per_page: 10
    problems:
      - type: "addition"
        operands: [2, 1] # Number of digits for each operand

  - output: "juna.tex"
    n_page: 10
    page_offset: 51
    questions_per_page: 20
    problems:
      - type: "addition"
        operands: [2, 2]

  - output: "bom.tex"
    n_page: 10
    page_offset: 51
    questions_per_page: 20
    problems:
      - type: "addition"
        operands: [3, 3]