generations:
  - output: "luna.tex"
    n_page: 10
    page_offset: 61
    problems:
      - type: "addition"
        operands: [2, 1] 
        questions_per_page: 10
      - type: "addition"
        operands: [1, 1]
        questions_per_page: 4

  - output: "juna.tex"
    n_page: 10
    page_offset: 61
    problems:
      - type: "addition"
        operands: [2, 2]
        questions_per_page: 20

  - output: "bom.tex"
    n_page: 10
    page_offset: 61
    problems:
      - type: "addition"
        operands: [3, 3]
        questions_per_page: 20